# Generated by Django 5.1.4 on 2024-12-23 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название папки')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название заметки')),
                ('note_text', models.TextField(max_length=50000, verbose_name='Текст заметки')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания')),
                ('date_of_editing', models.DateTimeField(verbose_name='Дата последнего изменения')),
                ('parent_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.folder', verbose_name='Родительская папка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
